### ISSUE TITLE
Build failures on Linux @ e058d5827d248b96532a862dfacadad34296367f

### ISSUE THREAD

**Issue by rdaum** [achaulk/retro_cpu#3]
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc: In member function ‘virtual bool WDC65C816::LoadState(const uint8_t**, const uint8_t*)’:
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:531:2: error: ‘memcpy’ was not declared in this scope
  memcpy(&s, *in_data, sizeof(s));
  ^~~~~~
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:531:2: note: suggested alternative: ‘wmemcpy’
  memcpy(&s, *in_data, sizeof(s));
  ^~~~~~
  wmemcpy
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:554:3: error: ‘memset’ was not declared in this scope
   memset(tracing.addrs.data(), 0, tracing.addrs.size() * sizeof(tracing.addrs[0]));
   ^~~~~~
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:554:3: note: suggested alternative: ‘wmemset’
   memset(tracing.addrs.data(), 0, tracing.addrs.size() * sizeof(tracing.addrs[0]));
   ^~~~~~
   wmemset
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc: In member function ‘virtual bool WDC65C816::DisassembleOneInstruction(const Disassembler::Config&, uint32_t&, CpuInstruction&)’:
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:586:13: error: ‘strlen’ was not declared in this scope
  auto len = strlen(str);
             ^~~~~~
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:586:13: note: suggested alternative: ‘mbrlen’
  auto len = strlen(str);
             ^~~~~~
             mbrlen
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:599:2: error: ‘memcpy’ was not declared in this scope
  memcpy(&insn.asm_string[n], str, len + 1);
  ^~~~~~
/home/ryan/c256emu/cmake-build-release/retrocpu-prefix/src/retrocpu/cpu/65816/cpu_65c816.cc:599:2: note: suggested alternative: ‘wmemcpy’
  memcpy(&insn.asm_string[n], str, len + 1);
  ^~~~~~
  wmemcpy

**Comment by achaulk** [comment]
Fixed now
